/* Generated by the Nim Compiler v2.3.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33555157 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555165 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555164 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555161 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555162 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
var NNI33555162 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555162.node = NNI33555162;
NTI33555164.base = NTI33555161;
NTI33555165.base = NTI33555161;
var NNI33555161 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555164, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555165, name: "up", sons: null}]};
NTI33555161.node = NNI33555161;
var NNI33555157 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555157.node = NNI33555157;
NTI33555161.base = NTI33555157;
NTI33555162.base = NTI33555161;
NTI134217745.base = NTI33555162;

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557319 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2867(ti_p2))) {
      result_33557319 = src_p1;
      }
      else {
        result_33557319 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557319 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557319 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557319 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557319 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557319, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557319 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557319 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557319 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557319[i] = nimCopy(result_33557319[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557319 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557319 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557319[i] = nimCopy(result_33557319[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557319 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557319 = src_p1;
      break;
    }

  return result_33557319;

}

function isObj(obj_p0, subclass_p1) {
  var result_33557432 = false;

  BeforeRet: {
    var x_33557433 = obj_p0;
    if ((x_33557433 == subclass_p1)) {
    result_33557432 = true;
    break BeforeRet;
    }
    
    Label1: {
        Label2: while (true) {
        if (!!((x_33557433 == subclass_p1))) break Label2;
          if ((x_33557433 == null)) {
          result_33557432 = false;
          break BeforeRet;
          }
          
          x_33557433 = x_33557433.base;
        }
    };
    result_33557432 = true;
    break BeforeRet;
  };

  return result_33557432;

}

function toJSStr(s_p0) {
  var result_33556908 = null;

    var res_33556962 = newSeq__system_u2505((s_p0).length);
    var i_33556963 = 0;
    var j_33556964 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556963 < (s_p0).length)) break Label2;
          var c_33556965 = s_p0[i_33556963];
          if ((c_33556965 < 128)) {
          res_33556962[j_33556964] = String.fromCharCode(c_33556965);
          i_33556963 += 1;
          }
          else {
            var helper_33556991 = newSeq__system_u2505(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556992 = c_33556965.toString(16);
                  if ((((code_33556992) == null ? 0 : (code_33556992).length) == 1)) {
                  helper_33556991.push("%0");;
                  }
                  else {
                  helper_33556991.push("%");;
                  }
                  
                  helper_33556991.push(code_33556992);;
                  i_33556963 += 1;
                  if ((((s_p0).length <= i_33556963) || (s_p0[i_33556963] < 128))) {
                  break Label3;
                  }
                  
                  c_33556965 = s_p0[i_33556963];
                }
            };
++excHandler;
            try {
            res_33556962[j_33556964] = decodeURIComponent(helper_33556991.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            raiseDefect();
            res_33556962[j_33556964] = helper_33556991.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556964 += 1;
        }
    };
    if (res_33556962.length < j_33556964) { for (var i = res_33556962.length ; i < j_33556964 ; ++i) res_33556962.push(null); }
               else { res_33556962.length = j_33556964; };
    result_33556908 = res_33556962.join("");

  return result_33556908;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    throw e_p0;

  
}

function isFatPointer__system_u2867(ti_p0) {
  var result_33557301 = false;

  BeforeRet: {
    result_33557301 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557301;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}

function add__system_u1934(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function newSeq__system_u2505(len_p0) {
  var result_33556941 = [];

    result_33556941 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556941[i] = null; }
  return result_33556941;

}

function isNimException__system_u2009() {
    return lastJSError && lastJSError.m_type;

  
}

function getCurrentException() {
  var result_33556444 = null;

    if (isNimException__system_u2009()) {
    result_33556444 = lastJSError;
    }
    

  return result_33556444;

}

function raiseDefect() {
    if (isNimException__system_u2009()) {
    var e_33556653 = getCurrentException();
    if (isObj(e_33556653.m_type, NTI33555162)) {
    if ((excHandler == 0)) {
    unhandledException(e_33556653);
    }
    
    throw e_33556653;
    }
    
    }
    

  
}

function unhandledException(e_p0) {
    var buf_33556647 = [[]];
    if (!(((e_p0.message).length == 0))) {
    buf_33556647[0].push.apply(buf_33556647[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556647[0].push.apply(buf_33556647[0], e_p0.message);;
    }
    else {
    buf_33556647[0].push.apply(buf_33556647[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556647[0].push.apply(buf_33556647[0], [32,91]);;
    add__system_u1934(buf_33556647, 0, e_p0.name);
    buf_33556647[0].push.apply(buf_33556647[0], [93,10]);;
    var cbuf_33556648 = toJSStr(buf_33556647[0]);
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556648);
  }
  else {
    throw cbuf_33556648;
  }
  

  
}

function sysFatal__stdZassertions_u41(message_p1) {
    raiseException({message: nimCopy(null, message_p1, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");

  
}

function raiseAssert__stdZassertions_u39(msg_p0) {
    sysFatal__stdZassertions_u41(msg_p0);

  
}

function failedAssertImpl__stdZassertions_u81(msg_p0) {
    raiseAssert__stdZassertions_u39(msg_p0);

  
}
if (false) {
failedAssertImpl__stdZassertions_u81([116,99,115,121,109,98,111,108,46,110,105,109,40,53,44,32,49,41,32,96,110,111,116,32,100,101,102,105,110,101,100,40,103,99,99,41,96,32]);
}

if (false) {
failedAssertImpl__stdZassertions_u81([116,99,115,121,109,98,111,108,46,110,105,109,40,54,44,32,49,41,32,96,110,111,116,32,100,101,102,105,110,101,100,40,116,99,99,41,96,32]);
}

